//==============================================
// File: solvra_script/ir/value.rs
// Author: Solvra Systems — Generated by Codex Agent
// License: Duality Public License (DPL v1.0)
// Goal: Represent SSA values and identifiers
// Objective: Define ValueId, InstructionId, constants, and metadata stored by SolvraIR
//==============================================

use crate::ir::types::{Ownership, TypeDescriptor};
use std::fmt;

/// Identifier for SSA values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ValueId(pub(crate) u32);

impl ValueId {
    pub fn index(self) -> usize {
        self.0 as usize
    }
}

impl fmt::Display for ValueId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "%{}", self.0)
    }
}

/// Identifier for SSA instructions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct InstructionId(pub(crate) u32);

impl InstructionId {
    pub fn index(self) -> usize {
        self.0 as usize
    }
}

impl From<InstructionId> for ValueId {
    fn from(instr: InstructionId) -> Self {
        ValueId(instr.0)
    }
}

/// Classification of an SSA value.
#[derive(Debug, Clone, PartialEq)]
pub enum ValueKind {
    Parameter(usize),
    Constant(ConstantValue),
    Instruction(InstructionId),
    BlockArgument,
}

/// Constant payload stored in SSA form.
#[derive(Debug, Clone, PartialEq)]
pub enum ConstantValue {
    Int(i64),
    Float(f64),
    Bool(bool),
    String(String),
    Null,
}

/// Complete metadata describing a value.
#[derive(Debug, Clone, PartialEq)]
pub struct ValueData {
    pub id: ValueId,
    pub ty: TypeDescriptor,
    pub ownership: Ownership,
    pub kind: ValueKind,
    pub debug_name: Option<String>,
}

impl ValueData {
    pub fn new(
        id: ValueId,
        ty: TypeDescriptor,
        ownership: Ownership,
        kind: ValueKind,
        debug_name: Option<String>,
    ) -> Self {
        Self {
            id,
            ty,
            ownership,
            kind,
            debug_name,
        }
    }
}

//==============================================
// End of file
//==============================================
