//==============================================
// File: solvra_script/ir/block.rs
// Author: Solvra Systems — Generated by Codex Agent
// License: Duality Public License (DPL v1.0)
// Goal: Store basic block metadata
// Objective: Track control-flow edges, sealed status, and instruction order
//==============================================

use crate::ir::ops::{Instruction, Terminator};
use std::fmt;

/// Identifier assigned to a [`BasicBlock`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BlockId(pub(crate) u32);

impl BlockId {
    pub fn index(self) -> usize {
        self.0 as usize
    }
}

impl fmt::Display for BlockId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "bb{}", self.0)
    }
}

/// SSA block storing instruction order and CFG state.
#[derive(Debug, Clone)]
pub struct BasicBlock {
    pub id: BlockId,
    pub name: Option<String>,
    pub instructions: Vec<Instruction>,
    pub terminator: Option<Terminator>,
    pub predecessors: Vec<BlockId>,
    pub successors: Vec<BlockId>,
    pub sealed: bool,
}

impl BasicBlock {
    pub fn new(id: BlockId, name: Option<String>) -> Self {
        Self {
            id,
            name,
            instructions: Vec::new(),
            terminator: None,
            predecessors: Vec::new(),
            successors: Vec::new(),
            sealed: false,
        }
    }
}

//==============================================
// End of file
//==============================================
