//==============================================
// File: solvra_script/ir/mod.rs
// Author: Solvra Systems — Generated by Codex Agent
// License: Duality Public License (DPL v1.0)
// Goal: Expose the SolvraScript IR module tree
// Objective: Re-export the SSA IR core types, builders, and utilities
//==============================================

pub mod block;
pub mod builder;
pub mod display;
pub mod function;
pub mod interpreter;
pub mod ir;
pub mod lowering;
pub mod ops;
pub mod types;
pub mod value;
pub mod verify;

//==============================================
// End of file
//==============================================
